### ISSUE TITLE
Nocturno Font Issue (Chrome)

### ISSUE THREAD

**Issue by daviddyess** [deptofdefense/code.mil.page#11]
The Nocturno font doesn't display correctly in Chrome unless is it formatted as svg. 

More specifically, the font is clipping halfway down and throws off padding, line height, and text background.

----Don't add this, see comment below----
`@media screen and (-webkit-min-device-pixel-ratio:0) {
@font-face {font-family: ‘Nocturno’;
  src: url({% if jekyll.environment == 'staging' %}{% else %}{{ site.baseurl}}{% endif %}{% link css/NocturnoDisplay-Reg.ttf %}) format('svg');
}}`

**Comment by daviddyess** [comment]
In PR #13 I appended format('svg'); to the current @font-face style, rather than a separate style. Fixes Chrome and not adverse effects showed up in other browsers.

**Comment by tomberek** [comment]
Merged #13, still need to have a fallback for font-family.

**Comment by readywater** [comment]
Fallback path should be. It might be worth making an img of the code.mil so it survives degradation.

For fallback
Nocturno -> Serif
Karla -> sans-serif

**Comment by tomberek** [comment]
Fallbacks added with d8ad7b0
