### ISSUE TITLE
Design details for hover states

### ISSUE THREAD

**Issue by readywater** [deptofdefense/code.mil.page#6]
Design out all hover states w/ animations

**Comment by readywater** [comment]
<img width="744" alt="screen shot 2017-04-17 at 1 31 57 pm" src="https://cloud.githubusercontent.com/assets/202041/25097369/4480c5e2-2372-11e7-9a6d-c054631f4186.png">
<img width="706" alt="screen shot 2017-04-17 at 1 31 53 pm" src="https://cloud.githubusercontent.com/assets/202041/25097370/4483312e-2372-11e7-9097-1772cee964dc.png">

**Comment by readywater** [comment]
![buttonhover](https://cloud.githubusercontent.com/assets/202041/25097645/6318092e-2373-11e7-8baf-93942eb7db88.gif)

**Comment by tomberek** [comment]
Should the FAQ links get underline?

**Comment by tomberek** [comment]
Closing as resolved
